services:
  postgres:
    container_name: lingc
    image: postgres:16.3-alpine3.19
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=Teste123!@#
      - POSTGRES_DB=lingc
    ports:
      - "5432:5432"
    volumes:
      - lingc:/var/lib/postgresql/data

volumes:
  lingc:
